Id: Discord.DiscordDevelopment
Name: Discord Development
AppMoniker: discord-development
Version: 0.0.7811
Publisher: Discord Inc.
Author: Discord Inc.
License: (c) 2021 Discord Inc.
LicenseUrl: https://discord.com/licenses
Description: Whether you’re part of a school club, gaming group, worldwide art community, or just a handful of friends that want to spend time together, Discord makes it easy to talk every day and hang out more often.
Homepage: https://discord.com/
Installers:
  - Arch: neutral
    Url: https://dl-development.discordapp.net/apps/win/0.0.7811/DiscordDevelopmentSetup.exe
    Sha256: 4da06b25fe0ba6fc55df74758ffed349419dd54fd5bc182d79645a087478899b
    InstallerType: exe
    Switches:
      Silent: /s
      SilentWithProgress: /s
